// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PersonalTimelineAPI.Data;

#nullable disable

namespace PersonalTimelineAPI.Migrations
{
    [DbContext(typeof(TimelineDbContext))]
    [Migration("20251124191340_AddSpotifyIntegration")]
    partial class AddSpotifyIntegration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("PersonalTimelineAPI.Models.ApiConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ApiConnections");
                });

            modelBuilder.Entity("PersonalTimelineAPI.Models.GitHubIntegration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubUsername")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("GitHubIntegrations");
                });

            modelBuilder.Entity("PersonalTimelineAPI.Models.TimelineEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceApi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("TimelineEntries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Education",
                            CreatedAt = new DateTime(2025, 11, 24, 19, 13, 39, 998, DateTimeKind.Utc).AddTicks(7280),
                            Description = "Began my journey into full-stack web development with .NET and React",
                            EntryType = "Milestone",
                            EventDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "",
                            ExternalUrl = "",
                            ImageUrl = "",
                            Metadata = "{}",
                            SourceApi = "Manual",
                            Title = "Started Learning Web Development",
                            UpdatedAt = new DateTime(2025, 11, 24, 19, 13, 39, 998, DateTimeKind.Utc).AddTicks(7280),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Projects",
                            CreatedAt = new DateTime(2025, 11, 24, 19, 13, 39, 998, DateTimeKind.Utc).AddTicks(7280),
                            Description = "Built a personal portfolio website using React and TypeScript",
                            EntryType = "Achievement",
                            EventDate = new DateTime(2024, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "",
                            ExternalUrl = "",
                            ImageUrl = "",
                            Metadata = "{}",
                            SourceApi = "Manual",
                            Title = "Completed First React Project",
                            UpdatedAt = new DateTime(2025, 11, 24, 19, 13, 39, 998, DateTimeKind.Utc).AddTicks(7280),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            Category = "Open Source",
                            CreatedAt = new DateTime(2025, 11, 24, 19, 13, 39, 998, DateTimeKind.Utc).AddTicks(7280),
                            Description = "Made my first open source contribution to a popular repository",
                            EntryType = "Achievement",
                            EventDate = new DateTime(2024, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "",
                            ExternalUrl = "https://github.com",
                            ImageUrl = "",
                            Metadata = "{}",
                            SourceApi = "Manual",
                            Title = "First GitHub Contribution",
                            UpdatedAt = new DateTime(2025, 11, 24, 19, 13, 39, 998, DateTimeKind.Utc).AddTicks(7280),
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Category = "Health",
                            CreatedAt = new DateTime(2025, 11, 24, 19, 13, 39, 998, DateTimeKind.Utc).AddTicks(7280),
                            Description = "Committed to a healthier lifestyle with daily exercise",
                            EntryType = "Milestone",
                            EventDate = new DateTime(2024, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "",
                            ExternalUrl = "",
                            ImageUrl = "",
                            Metadata = "{}",
                            SourceApi = "Manual",
                            Title = "Started Fitness Journey",
                            UpdatedAt = new DateTime(2025, 11, 24, 19, 13, 39, 998, DateTimeKind.Utc).AddTicks(7280),
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            Category = "Music",
                            CreatedAt = new DateTime(2025, 11, 24, 19, 13, 39, 998, DateTimeKind.Utc).AddTicks(7280),
                            Description = "Fell in love with indie folk music",
                            EntryType = "Memory",
                            EventDate = new DateTime(2024, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExternalId = "",
                            ExternalUrl = "",
                            ImageUrl = "",
                            Metadata = "{}",
                            SourceApi = "Manual",
                            Title = "Discovered New Music Genre",
                            UpdatedAt = new DateTime(2025, 11, 24, 19, 13, 39, 998, DateTimeKind.Utc).AddTicks(7280),
                            UserId = 1
                        });
                });

            modelBuilder.Entity("PersonalTimelineAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OAuthId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OAuthProvider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 24, 19, 13, 39, 998, DateTimeKind.Utc).AddTicks(7230),
                            DisplayName = "Test User",
                            Email = "testuser@example.com",
                            LastLoginAt = new DateTime(2025, 11, 24, 19, 13, 39, 998, DateTimeKind.Utc).AddTicks(7230),
                            Name = "",
                            OAuthId = "test-oauth-id-123",
                            OAuthProvider = "Google",
                            Picture = "",
                            ProfileImageUrl = "https://via.placeholder.com/150"
                        });
                });

            modelBuilder.Entity("SpotifyIntegration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ConnectedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SpotifyIntegrations");
                });

            modelBuilder.Entity("PersonalTimelineAPI.Models.ApiConnection", b =>
                {
                    b.HasOne("PersonalTimelineAPI.Models.User", "User")
                        .WithMany("ApiConnections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalTimelineAPI.Models.GitHubIntegration", b =>
                {
                    b.HasOne("PersonalTimelineAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalTimelineAPI.Models.TimelineEntry", b =>
                {
                    b.HasOne("PersonalTimelineAPI.Models.User", "User")
                        .WithMany("TimelineEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PersonalTimelineAPI.Models.User", b =>
                {
                    b.Navigation("ApiConnections");

                    b.Navigation("TimelineEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
